#!/usr/bin/env node
// Regenerate the keyword block in syntax/gnuplot.vim from keywords.json.
//
// keywords.json is a pinned copy of the dictionary emitted by the
// tree-sitter-gnuplot grammar (scripts/gen-keywords.mjs there). Every entry
// carries the keyword, its highlight tier, and the shortest abbreviation
// gnuplot accepts. Vim's `syn keyword` understands `xr[ange]` natively, which
// is exactly that abbreviation rule — so the whole table becomes plain keyword
// lists with no regex at all.
//
// Usage: node scripts/gen-syntax.mjs [--check]

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SYNTAX = join(root, "syntax", "gnuplot.vim");
const BEGIN = '" >>> generated by scripts/gen-syntax.mjs — do not edit by hand';
const END = '" <<< end generated block';

// Tier -> syntax group. Mirrors the capture taxonomy documented in the grammar
// repo: the same word in two clause families gets two aliases there, but Vim
// keywords are context-free, so tiers that read the same way share a group.
const GROUP = {
  cmd: "gnuplotCommand",
  opt: "gnuplotOption",
  arg: "gnuplotOption",
  name: "gnuplotOption",
  axis: "gnuplotOption",
  sa: "gnuplotOption",
  lt: "gnuplotOption",
  lc: "gnuplotOption",
  dt: "gnuplotOption",
  pt: "gnuplotOption",
  ps: "gnuplotOption",
  fs: "gnuplotOption",
  fc: "gnuplotOption",
  tc: "gnuplotOption",
  flag: "gnuplotFlag",
  coord: "gnuplotFlag",
  mod: "gnuplotValue",
  attr: "gnuplotAttribute",
  plt_st: "gnuplotStyle",
  st_opt: "gnuplotStyle",
};

// A word may legitimately belong to several tiers (`border` is an option head,
// a body flag and a suboption). Vim cannot tell those apart without the
// context matching this file deliberately avoids, so the first tier listed
// here wins and the choice is recorded in the generated output.
const PRIORITY = [
  "cmd",
  "opt",
  "plt_st",
  "st_opt",
  "attr",
  "coord",
  "mod",
  "flag",
  "arg",
  "name",
  "axis",
  "sa",
  "lt",
  "lc",
  "dt",
  "pt",
  "ps",
  "fs",
  "fc",
  "tc",
];

// The table stores `min <= 0` as "full word minus |min|".
const effMin = (e) => (e.min <= 0 ? e.kw.length + e.min : e.min);

// "xrange" with a minimum of 2 becomes `xr[ange]`; a keyword that takes no
// abbreviation is emitted bare.
function form(word, min) {
  const m = Math.max(1, Math.min(min, word.length));
  return m >= word.length ? word : `${word.slice(0, m)}[${word.slice(m)}]`;
}

function build() {
  const { keywords } = JSON.parse(readFileSync(join(root, "keywords.json"), "utf8"));

  // resolve each word to a single tier
  const chosen = new Map();
  for (const e of keywords) {
    const prev = chosen.get(e.kw);
    if (!prev || PRIORITY.indexOf(e.tier) < PRIORITY.indexOf(prev.tier)) chosen.set(e.kw, e);
  }

  const buckets = new Map();
  const add = (group, text) => {
    if (!buckets.has(group)) buckets.set(group, new Set());
    buckets.get(group).add(text);
  };

  for (const e of chosen.values()) {
    const group = GROUP[e.tier];
    if (!group) throw new Error(`no group for tier ${e.tier} (${e.kw})`);
    add(group, form(e.kw, effMin(e)));
    // `lw`, `ls`, `tc` … — fixed two-letter spellings, never abbreviated
    if (e.alt) add(group, e.alt);
    // toggles also exist in their `no` spelling
    if (e.no) add(group, `no${form(e.kw, effMin(e))}`);
  }

  // Vim resolves a keyword defined twice to the LAST definition, so emit the
  // groups in reverse priority: whichever tier should win a collision is
  // written last. `p` is both `p[lot]` and `p[oints]`, and a command verb at
  // the start of a statement is the more valuable of the two to get right.
  const ORDER = [
    "gnuplotValue",
    "gnuplotFlag",
    "gnuplotOption",
    "gnuplotStyle",
    "gnuplotAttribute",
    "gnuplotCommand",
  ];
  const groups = [...buckets.keys()].sort(
    (x, y) => ORDER.indexOf(x) - ORDER.indexOf(y)
  );

  const lines = [BEGIN];
  lines.push(
    `" ${chosen.size} keywords across ${buckets.size} groups. Regenerate with`,
    '" `npm run gen:syntax` after updating keywords.json.',
    '" Groups are emitted in reverse-priority order: Vim resolves a keyword',
    '" defined twice to the last definition.'
  );
  for (const group of groups) {
    const words = [...buckets.get(group)].sort();
    lines.push("");
    let line = `syn keyword ${group}`;
    for (const w of words) {
      if (line.length + w.length + 1 > 78) {
        lines.push(line);
        line = `syn keyword ${group}`;
      }
      line += ` ${w}`;
    }
    if (line.trim()) lines.push(line);
  }
  lines.push(END);
  return lines.join("\n");
}

const block = build();
const current = readFileSync(SYNTAX, "utf8");
const start = current.indexOf(BEGIN);
const stop = current.indexOf(END);
if (start < 0 || stop < 0) throw new Error(`markers missing in ${SYNTAX}`);
const next = current.slice(0, start) + block + current.slice(stop + END.length);

if (process.argv.includes("--check")) {
  if (next !== current) {
    console.error("syntax/gnuplot.vim is stale — run `npm run gen:syntax`");
    process.exit(1);
  }
  console.log("syntax/gnuplot.vim is up to date");
} else {
  writeFileSync(SYNTAX, next);
  console.log(`wrote ${SYNTAX}`);
}
